### ISSUE TITLE
shopifyCustomer.customerUpdate returns error

### ISSUE THREAD

**Issue by emvaized** [ThinkSimple/flutter_simple_shopify#14]
Here's the method I'm trying to use:
`shopifyCustomer.customerUpdate(firstName: _firstName);`

Here's the error I get:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: GraphQL Errors:
E/flutter ( 8930): Variable $acceptsMarketing is declared by customerUpdate but not used: Undefined location
E/flutter ( 8930): #0      ShopifyError.checkForError (package:flutter_simple_shopify/mixins/src/shopfiy_error.dart:6:7)
E/flutter ( 8930): #1      ShopifyCustomer.customerUpdate (package:flutter_simple_shopify/shopify/src/shopify_customer.dart:76:5)
E/flutter ( 8930): <asynchronous suspension>
...
```

Have tried to pass `acceptsMarketing: false` parameter to the method as well, but error still occurs.

**Comment by ThinkSimple** [comment]
I pushed a new update, can you try again?

**Comment by emvaized** [comment]
@ThinkSimple 
No error happens anymore!
However, `shopifyCustomer.customerUpdate(firstName: _firstName);` seems to change nothing - first name remains the same.

Maybe that's because I'm not passing any `customerAccessToken` value to the constructor?

**Comment by ThinkSimple** [comment]
Did you try to pass it in?

**Comment by emvaized** [comment]
@ThinkSimple 
Yes. I've take a look in the source code, and tried to do something like this:
```
String _accessToken = (await SharedPreferences.getInstance()).getString('FLUTTER_SIMPLE_SHOPIFY_ACCESS_TOKEN');
await shopifyCustomer.customerUpdate(firstName: _firstName, customerAccessToken: _accessToke );
```
But still no effect - account's name remains the same on the website.

**Comment by Unown-Fashion** [comment]
@ThinkSimple 
Any updates on it? Just faced this issue.

**Comment by ThinkSimple** [comment]
Updated the Library.

The problem was that you had to populate all wanted fields now it seems to work even when you only change one field.
Please make sure you have a valid customer access token, since they expire pretty fast,
Shopify validates each field on their server that means that you might face problems changing fields such as email or phone number because they need to be in a specific format, eg phone number starting with "+" (i think) or emails having a "@".

If new problems come up please open up new issue

**Comment by emvaized** [comment]
Thanks a lot!
When expect it to come in package update?

**Comment by ThinkSimple** [comment]
Just updated, should be in the 0.22

**Comment by ThinkSimple** [comment]
Just seen that it didnt go through, my bad.
Will update tomorrow or if i manage to later.

**Comment by ThinkSimple** [comment]
updated right now

**Comment by emvaized** [comment]
Thanks a lot! I can confirm it's working - website displays updated name correctly 👍

Important note for anyone revisiting this: in order to display updated values in the app, don't forget to pass `deleteThisPartOfCache: true` parameter to `shopifyAuth.currentUser()`.

**Comment by hetkpatel** [comment]
I tried implementing `customerUpdate()` but I keep getting this error:

```
flutter: mutation myNewMutation($firstName: String,$customerAccessToken: String!) {
  customerUpdate(customer: {firstName: $firstName}, customerAccessToken: $customerAccessToken) {
    customerUserErrors {
      code
      field
      message
    }
  }
}
```

Don't know how to grab the `customerUserErrors.message` and see what's actually wrong

**Comment by emvaized** [comment]
@hetkpatel 
I faced similar issue with the checkout methods, but it seems that case was easier - maybe will give you some ideas however:
[https://github.com/ThinkSimple/flutter_simple_shopify/issues/32](https://github.com/ThinkSimple/flutter_simple_shopify/issues/32)

**Comment by emvaized** [comment]
@ThinkSimple 
It seems that `customerAddressCreate` and `customerAddressUpdate` seem to have similar issue, as changed data can not be seen on the website. Maybe those need your patch as well?
